ResNetTreeStructure = [{'module_name': 'res_net18/~/block_group_0/~/block_0/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 64, 64),
                        'size': 36864,
                        'i_0': 0,
                        'i_1': 36864},
                       {'module_name': 'res_net18/~/block_group_0/~/block_0/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 64, 64),
                        'size': 36864,
                        'i_0': 36864,
                        'i_1': 73728},
                       {'module_name': 'res_net18/~/block_group_0/~/block_1/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 64, 64),
                        'size': 36864,
                        'i_0': 73728,
                        'i_1': 110592},
                       {'module_name': 'res_net18/~/block_group_0/~/block_1/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 64, 64),
                        'size': 36864,
                        'i_0': 110592,
                        'i_1': 147456},
                       {'module_name': 'res_net18/~/block_group_1/~/block_0/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 64, 128),
                        'size': 73728,
                        'i_0': 147456,
                        'i_1': 221184},
                       {'module_name': 'res_net18/~/block_group_1/~/block_0/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 128, 128),
                        'size': 147456,
                        'i_0': 221184,
                        'i_1': 368640},
                       {'module_name': 'res_net18/~/block_group_1/~/block_0/~/shortcut_conv',
                        'param_name': 'w',
                        'shape': (1, 1, 64, 128),
                        'size': 8192,
                        'i_0': 368640,
                        'i_1': 376832},
                       {'module_name': 'res_net18/~/block_group_1/~/block_1/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 128, 128),
                        'size': 147456,
                        'i_0': 376832,
                        'i_1': 524288},
                       {'module_name': 'res_net18/~/block_group_1/~/block_1/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 128, 128),
                        'size': 147456,
                        'i_0': 524288,
                        'i_1': 671744},
                       {'module_name': 'res_net18/~/block_group_2/~/block_0/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 128, 256),
                        'size': 294912,
                        'i_0': 671744,
                        'i_1': 966656},
                       {'module_name': 'res_net18/~/block_group_2/~/block_0/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 256, 256),
                        'size': 589824,
                        'i_0': 966656,
                        'i_1': 1556480},
                       {'module_name': 'res_net18/~/block_group_2/~/block_0/~/shortcut_conv',
                        'param_name': 'w',
                        'shape': (1, 1, 128, 256),
                        'size': 32768,
                        'i_0': 1556480,
                        'i_1': 1589248},
                       {'module_name': 'res_net18/~/block_group_2/~/block_1/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 256, 256),
                        'size': 589824,
                        'i_0': 1589248,
                        'i_1': 2179072},
                       {'module_name': 'res_net18/~/block_group_2/~/block_1/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 256, 256),
                        'size': 589824,
                        'i_0': 2179072,
                        'i_1': 2768896},
                       {'module_name': 'res_net18/~/block_group_3/~/block_0/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 256, 512),
                        'size': 1179648,
                        'i_0': 2768896,
                        'i_1': 3948544},
                       {'module_name': 'res_net18/~/block_group_3/~/block_0/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 512, 512),
                        'size': 2359296,
                        'i_0': 3948544,
                        'i_1': 6307840},
                       {'module_name': 'res_net18/~/block_group_3/~/block_0/~/shortcut_conv',
                        'param_name': 'w',
                        'shape': (1, 1, 256, 512),
                        'size': 131072,
                        'i_0': 6307840,
                        'i_1': 6438912},
                       {'module_name': 'res_net18/~/block_group_3/~/block_1/~/conv_0',
                        'param_name': 'w',
                        'shape': (3, 3, 512, 512),
                        'size': 2359296,
                        'i_0': 6438912,
                        'i_1': 8798208},
                       {'module_name': 'res_net18/~/block_group_3/~/block_1/~/conv_1',
                        'param_name': 'w',
                        'shape': (3, 3, 512, 512),
                        'size': 2359296,
                        'i_0': 8798208,
                        'i_1': 11157504},
                       {'module_name': 'res_net18/~/initial_conv',
                        'param_name': 'w',
                        'shape': (7, 7, 3, 64),
                        'size': 9408,
                        'i_0': 11157504,
                        'i_1': 11166912},
                       {'module_name': 'res_net18/~/logits',
                        'param_name': 'b',
                        'shape': (100,),
                        'size': 100,
                        'i_0': 11166912,
                        'i_1': 11167012},
                       {'module_name': 'res_net18/~/logits',
                        'param_name': 'w',
                        'shape': (512, 100),
                        'size': 51200,
                        'i_0': 11167012,
                        'i_1': 11218212}]

ConvDropoutTreeStructure = [{'module_name': 'conv_dropout_module/conv2_d',
                             'param_name': 'b',
                             'shape': (32,),
                             'size': 32,
                             'i_0': 0,
                             'i_1': 32},
                            {'module_name': 'conv_dropout_module/conv2_d',
                             'param_name': 'w',
                             'shape': (3, 3, 1, 32),
                             'size': 288,
                             'i_0': 32,
                             'i_1': 320},
                            {'module_name': 'conv_dropout_module/conv2_d_1',
                             'param_name': 'b',
                             'shape': (64,),
                             'size': 64,
                             'i_0': 320,
                             'i_1': 384},
                            {'module_name': 'conv_dropout_module/conv2_d_1',
                             'param_name': 'w',
                             'shape': (3, 3, 32, 64),
                             'size': 18432,
                             'i_0': 384,
                             'i_1': 18816},
                            {'module_name': 'conv_dropout_module/linear',
                             'param_name': 'b',
                             'shape': (128,),
                             'size': 128,
                             'i_0': 18816,
                             'i_1': 18944},
                            {'module_name': 'conv_dropout_module/linear',
                             'param_name': 'w',
                             'shape': (9216, 128),
                             'size': 1179648,
                             'i_0': 18944,
                             'i_1': 1198592},
                            {'module_name': 'conv_dropout_module/linear_1',
                             'param_name': 'b',
                             'shape': (62,),
                             'size': 62,
                             'i_0': 1198592,
                             'i_1': 1198654},
                            {'module_name': 'conv_dropout_module/linear_1',
                             'param_name': 'w',
                             'shape': (128, 62),
                             'size': 7936,
                             'i_0': 1198654,
                             'i_1': 1206590}]

LSTMTreeStructure = [{'module_name': 'embed',
                      'param_name': 'embeddings',
                      'shape': (10004, 96),
                      'size': 960384,
                      'i_0': 0,
                      'i_1': 960384},
                     {'module_name': 'linear',
                      'param_name': 'b',
                      'shape': (96,),
                      'size': 96,
                      'i_0': 960384,
                      'i_1': 960480},
                     {'module_name': 'linear',
                      'param_name': 'w',
                      'shape': (670, 96),
                      'size': 64320,
                      'i_0': 960480,
                      'i_1': 1024800},
                     {'module_name': 'linear_1',
                      'param_name': 'b',
                      'shape': (10004,),
                      'size': 10004,
                      'i_0': 1024800,
                      'i_1': 1034804},
                     {'module_name': 'linear_1',
                      'param_name': 'w',
                      'shape': (96, 10004),
                      'size': 960384,
                      'i_0': 1034804,
                      'i_1': 1995188},
                     {'module_name': 'lstm/linear',
                      'param_name': 'b',
                      'shape': (2680,),
                      'size': 2680,
                      'i_0': 1995188,
                      'i_1': 1997868},
                     {'module_name': 'lstm/linear',
                      'param_name': 'w',
                      'shape': (766, 2680),
                      'size': 2052880,
                      'i_0': 1997868,
                      'i_1': 4050748}]

LRTreeStructure = [{'module_name': 'mlp/~/linear_0',
                    'param_name': 'b',
                    'shape': (500,),
                    'size': 500,
                    'i_0': 0,
                    'i_1': 500},
                   {'module_name': 'mlp/~/linear_0',
                    'param_name': 'w',
                    'shape': (10000, 500),
                    'size': 5000000,
                    'i_0': 500,
                    'i_1': 5000500}]

SimpleModelTreeStructure = [{'module_name': 'mlp/~/linear_0',
                             'param_name': 'b',
                             'shape': (100,),
                             'size': 100,
                             'i_0': 0,
                             'i_1': 100},
                            {'module_name': 'mlp/~/linear_0',
                             'param_name': 'w',
                             'shape': (100, 100),
                             'size': 10000,
                             'i_0': 100,
                             'i_1': 10100}]
